### ISSUE TITLE
Gauss gun reflect death error

### ISSUE THREAD

**Issue by Python1320** [TheMostUpset/Half-Life-SWEPs#1] opened 2019-05-13 20:14 UTC
Somehow reflect shoot yourself and you get
```lua
lua/weapons/weapon_hl1_gauss.lua:352: attempt to call method 'LagCompensation' (a nil value)
  1. GaussFire - lua/weapons/weapon_hl1_gauss.lua:352
   2. StartFire - lua/weapons/weapon_hl1_gauss.lua:333
    3. SpecialThink - lua/weapons/weapon_hl1_gauss.lua:238
     4. unknown - lua/weapons/weapon_hl1_base.lua:711

```

**Comment by TheMostUpset** [comment] 2019-05-14 07:20
Can't reproduce. Any other addons installed?

**Comment by Python1320** [comment] 2019-05-15 15:57
No other addons. Haven't had time to check but may have something to do with reflections.
```
map gm_flatgrass
sbox_godmode 0
sv_cheats 1
setpos -868.599426 21.316036 -12223.968750;setang 40.700069 77.307907 0.000000
```
Charge up and shoot and you should die. I cannot reproduce the error either. It may require srcds or somesuch.

**Comment by TheMostUpset** [comment] 2019-05-15 17:30
No error on srcds without addons.

**Comment by TheMostUpset** [comment] 2020-10-16 18:00
I've finally updated the github repo with all latest changes, this should be fixed.

**Closed as completed by TheMostUpset** 2020-10-16 18:00 UTC
